version: '3.9'
services:

  postgres_db:
    container_name: pg_db
    image: postgres:14-alpine
    environment:
        - POSTGRES_USER=${DB_USER}
        - POSTGRES_PASSWORD=${DB_PASS}
        - POSTGRES_DB=${DB_NAME}
    ports:
      - 5444:5432

  application:
    container_name: my_application
    build:
      context: .
    command: bash -c "sleep 10 && alembic revision --autogenerate && alembic upgrade head && python main.py"
    depends_on:
      - postgres_db

    ports:
      - 8005:8000
    env_file:
      - .env

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
    - PGADMIN_DEFAULT_EMAIL=noemail@noemail.com
    - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5151:80
    depends_on:
      - application
